# $HOME/.config/alacritty/alacritty.toml
# Joeworks Dotfiles (https://github.com/joelee/Dotfiles)
#

[window]
opacity = 0.88

padding.x = 8
padding.y = 8

class.instance = "Alacritty"
class.general = "Alacritty"

[scrolling]
history = 50000
multiplier = 3

[shell]
program = "/opt/homebrew/bin/fish"

[[keyboard.bindings]]
action = "IncreaseFontSize"
key = "Equals"
mods = "Control"

[[keyboard.bindings]]
action = "DecreaseFontSize"
key = "Minus"
mods = "Control"

[[keyboard.bindings]]
action = "ResetFontSize"
key = "Key0"
mods = "Control"

[[keyboard.bindings]]
action = "ToggleFullscreen"
key = "F11"

[[keyboard.bindings]]
action = "Copy"
key = "C"
mods = "Control|Shift"

[[keyboard.bindings]]
action = "Paste"
key = "V"
mods = "Control|Shift"

[colors.bright]
black = "#545454"
blue = "#94bff3"
cyan = "#93e0e3"
green = "#8ae234"
magenta = "#b294bb"
red = "#fc5454"
white = "#ffffff"
yellow = "#fce94f"

[colors.normal]
black = "#3f3f3f"
blue = "#94bff3"
cyan = "#06989a"
green = "#4e9a06"
magenta = "#85678f"
red = "#cc0000"
white = "#dcdccc"
yellow = "#c4a000"

[colors.primary]
background = "#222222"
foreground = "#F9F9F9"

[font]
size = 11.0

[font.bold]
family = "SauceCodePro NF"
style = "Bold"

[font.bold_italic]
family = "SauceCodePro NF"
style = "Bold Italic"

[font.italic]
family = "SauceCodePro NF"
style = "Italic"

[font.normal]
family = "SauceCodePro NF"
style = "Regular"
