# $HOME/.config/alacritty/alacritty.toml
# Joeworks Dotfiles (https://github.com/joelee/Dotfiles)
#

[window]
opacity = 0.81

padding.x = 8
padding.y = 8

class.instance = "Alacritty"
class.general = "Alacritty"


[scrolling]
history = 20000
multiplier = 3

[[keyboard.bindings]]
action = "IncreaseFontSize"
key = "Equals"
mods = "Control"

[[keyboard.bindings]]
action = "DecreaseFontSize"
key = "Minus"
mods = "Control"

[[keyboard.bindings]]
action = "ResetFontSize"
key = "Key0"
mods = "Control"

[[keyboard.bindings]]
action = "Copy"
key = "C"
mods = "Control|Shift"

[[keyboard.bindings]]
action = "Paste"
key = "V"
mods = "Control|Shift"
