# ~/.config/helix/languages.toml

##############################
# Python with Ruff, PyRight & Pylyzer
##############################
[[language]]
name = "python"
language-id = "python"
scope = "source.python"
injection-regex = "python"
file-types = ["py", "ipynb"]
roots = [
  "pyproject.toml",
  "setup.py",
  "poetry.lock",
  "requirements.txt",
  ".git",
]
comment-token = "#"
shebangs = ["python"]
indent = { tab-width = 4, unit = "  " }
language-servers = ["pyright", "ruff", "pylyzer"]
formatter = { command = "ruff", args = ["format", "-"] }


[language-server.pyright]
command = "pyright-langserver"
args = ["--stdio"]

[language-server.pyright.config.python.analysis]
typeCheckingMode = "basic"

[language-server.ruff]
command = "ruff"
args = ["server"]
environment = { "RUFF_TRACE" = "messages" }

[language-server.ruff.config.settings]
lineLength = 88
logLevel = "debug"

[language-server.ruff.config.settings.lint]
select = [
  "E",
  "F",
  "W",
  "B",
  "I",
  "RUF",
  "N",
  "LOG",
  "ERA",
  "D",
  "UP",
  "ANN",
  "ASYNC",
  "S",
  "RET",
  "TCH",
  "ARG",
  "PTH",
  "DOC",
]
preview = true

[language-server.ruff.config.settings.format]
preview = true
quote-style = "double"
docstring-code-format = true
indent-style = "space"

[language-server.pylyzer]
command = "pylyzer"
args = ["--server"]

##############################
# TOML with taplo
##############################
[[language]]
name = "toml"
file-types = ["toml"]
language-servers = ["taplo"]

[language-server.taplo]
command = "taplo"
args = ["lsp", "stdio"]


##############################
# YAML with yamlls
##############################
[[language]]
name = "yaml"
scope = "source.yaml"
file-types = ["yml", "yaml"]
comment-token = "#"

language-servers = ["yamlls"]
formatter = { command = "prettier", args = ["--parser", "yaml"] }

[language-server.yamlls]
command = "yaml-language-server"
args = ["--stdio"]

##############################
# JSON with jsonls
##############################
[[language]]
name = "json"
scope = "source.json"
file-types = ["json"]
language-servers = [
  { name = 'biome' },
  { name = "jsonls", except-features = [ "format" ] }
]
formatter = { command = "biome", args = ["format", "--stdin-file-path", "a.json"] }


[language-server.jsonls]
command = "vscode-json-language-server"
args = ["--stdio"]

[language-server.biome]
command = "biome"
args = ["lsp-proxy"]
display-messages = true

##############################
# Rust with rust-analyzer + rustfmt
##############################
[[language]]
name = "rust"
scope = "source.rust"
file-types = ["rs"]
roots = ["Cargo.toml", "rust-project.json", ".git"]
language-servers = ["rust-analyzer"]
formatter = { command = "rustfmt", args = ["--edition", "2021"] }

[language-server.rust-analyzer]
command = "rust-analyzer"

[language-server.rust-analyzer.config.check]
command = "clippy"

[language-server.rust-analyzer.config.cargo]
features = "all"

##############################
# JavaScript with TSS + Biome
##############################
[[language]]
name = "javascript"
scope = "source.javascript"
file-types = ["js", "mjs", "cjs"]
comment-token = "//"
language-servers = ["typescript-language-server"]
formatter = { command = "biome", args = [
  "format",
  "--stdin-file-path",
  "{buffer_path}",
] }


##############################
# JSX (React) with TSS + Prettier
##############################
[[language]]
name = "jsx"
scope = "source.jsx"
file-types = ["jsx"]
comment-token = "//"
language-servers = ["typescript-language-server"]
formatter = { command = "biome", args = [
  "format",
  "--stdin-file-path",
  "{buffer_path}",
] }


##############################
# TypeScript with TSS + Prettier
##############################
[[language]]
name = "typescript"
scope = "source.ts"
file-types = ["ts"]
comment-token = "//"
language-servers = ["typescript-language-server"]
formatter = { command = "biome", args = [
  "format",
  "--stdin-file-path",
  "{buffer_path}",
] }

##############################
# TSX (React) with TSS + Prettier
##############################
[[language]]
name = "tsx"
scope = "source.tsx"
file-types = ["tsx"]
comment-token = "//"
language-servers = ["typescript-language-server"]
formatter = { command = "biome", args = [
  "format",
  "--stdin-file-path",
  "{buffer_path}",
] }

[language-server.typescript-language-server]
command = "typescript-language-server"
args = ["--stdio"]

##############################
# Bash (bash-language-server + shfmt)
##############################
[[language]]
name = "bash"
file-types = ["sh", "bash", "bats"]
roots = [".git"]
language-servers = ["bash-language-server"]
formatter = { command = "shfmt", args = ["-filename", "{buffer_path}"] }

[language-server.bash-language-server]
command = "bash-language-server"
args = ["start"]

##############################
# Terraform (terraform-ls + terraform fmt)
##############################
[[language]]
name = "tfvars"
language-id = "terraform-vars"
file-types = ["tfvars"]
roots = ["main.tf", ".terraform", ".git"]
language-servers = ["terraform-ls"]
# `terraform fmt -` reads from stdin and writes to stdout
formatter = { command = "terraform", args = ["fmt", "-"] }

[[language]]
name = "hcl"
language-id = "terraform"
file-types = ["tf"]
roots = ["main.tf", ".terraform", ".git"]
language-servers = ["terraform-ls"]
# `terraform fmt -` reads from stdin and writes to stdout
formatter = { command = "terraform", args = ["fmt", "-"] }

[language-server.terraform-ls]
command = "terraform-ls"
args = ["serve"]
# config.indexing.ignorePaths = ["ignore.hcl"]


##############################
# SQL (sql-formatter)
##############################
[[language]]
name = "sql"
file-types = ["sql"]
# Use the Node.js sql-formatter CLI (reads from stdin, writes to stdout)
formatter = { command = "sql-formatter" }
auto-format = true
language-servers = ["sqlls"]

[language-server.sqlls]
command = "sql-language-server"
args = ["up", "--method", "stdio"]
